# Generated by Django 4.1.5 on 2023-01-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_alter_like_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегория', 'verbose_name_plural': 'Подкатегории'},
        ),
    ]
