# Generated by Django 4.1.5 on 2023-01-10 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_alter_subcategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='themes.category'),
            preserve_default=False,
        ),
    ]
